add httpClient
alkemyTech/OT-90-Client pull request #12
Opened 2021-11-02 23:22 UTC by benjaminPla

COMO: Desarrollador
QUIERO: Tener un servicio reutilizable
PARA: Manejar las peticiones a la api

Criterios de aceptación: Crear un servicio reutilizable para manejar las peticiones a la API, inicialmente los métodos GET y POST. Como manejaremos el estado de autenticación utilizando JWT, deberá verificar si existe una clave "token" en localStorage, y en el caso de que exista, agregarla en los encabezados de las peticiones.

--

1. Add httpClient.js file.
2. Add axios to package.json
2. Modify and form test porpouses Component/Header.jsx.
3. Rollback changes of Component/Header.jsx

<img width="1280" alt="Screen Shot 2021-11-02 at 08 53 10" src="https://user-images.githubusercontent.com/85419447/139965205-419e5a28-9c46-476c-b45a-fe120c2955c7.png">
<img width="1280" alt="Screen Shot 2021-11-02 at 08 53 34" src="https://user-images.githubusercontent.com/85419447/139965213-b9438c03-3520-45cd-9e4b-e6a0a7029d13.png">
<img width="1280" alt="Screen Shot 2021-11-02 at 08 53 55" src="https://user-images.githubusercontent.com/85419447/139965215-aad16cc9-c4e1-4c49-8429-03123ec615d1.png">
<img width="1280" alt="Screen Shot 2021-11-02 at 08 54 35" src="https://user-images.githubusercontent.com/85419447/139965216-3e0c80d1-359e-47b4-aef7-82da455a5045.png">

2021-11-03 10:29 UTC, andresmonsa approved these changes

2021-11-03 10:29 UTC, andresmonsa commented on src/httpClient.js
> +  if (!userData.token) return { error: 'no token' }
Si no hay token corta la ejecución pero debería poder realizarse la petición igual.

2021-11-03 13:47 UTC, dvelezroman requested changes

2021-11-03 13:47 UTC, dvelezroman commented on src/httpClient.js
> +  if (!userData.token) return { error: 'no token' }
claro,, si no hay token.. deberia ejecutarse la peticion ... ya que se trataria de una request tipo GET o una que no necesite token
y es el server con su middleware que ese encargara de dejar pasar o no la request y devolver respuesta o error.

2021-11-03 21:45 UTC, dvelezroman requested changes

2021-11-03 21:45 UTC, dvelezroman commented on src/httpClient.js
> +export default async function request(method, url) {
falta parametros para el body ... cuando es POST, PUT ....

2021-11-03 21:45 UTC, dvelezroman commented on src/httpClient.js
> +  const token = `Bearer  ${userData.token}`
`const headers = { Authorization: token }`

2021-11-03 21:45 UTC, dvelezroman commented on src/httpClient.js
> +  const response = await axios({ method, url, headers: { Authorization: token } })
`const body = { ...params }`

2021-11-03 21:45 UTC, dvelezroman commented on src/httpClient.js
> +
const baseUrl =
  process.env.NODE_ENV === 'production'
    ? process.env.REACT_APP_BASE_URL_PROD
    : process.env.REACT_APP_BASE_URL_LOCAL

export const sendRequest = async (method, relativeUrl, data) => {
  const url = baseUrl + relativeUrl

2021-11-05 13:22 UTC, andresmonsa approved these changes

2021-11-05 19:36 UTC, dvelezroman approved these changes
Hay que probarlo una vez mergeado

2021-11-05 22:49 UTC, marcelonieva7 requested changes

2021-11-05 22:49 UTC, marcelonieva7 commented on package.json
> -    "react-aws-s3": "1.5.0",
dependencia aws borrada

2021-11-08 14:26 UTC, merged