OT90-673 (Component/UserFormPUT.jsx)
alkemyTech/OT-90-Client pull request #26
Opened 2021-11-10 12:38 UTC by benjaminPla

Formulario edicion usuario

COMO: Usuario administrador
QUIERO: Actualizar un usuario
PARA: Mantener los datos de usuarios del proyecto actualizados

Criterios de aceptación: Este formulario permitirá editar los datos del usuario, y se utilizará en 2 páginas: Editar mi perfil (para todos los usuarios autenticados), y Editar Usuario desde el Backoffice, cuando el administrador quiera editar cualquier usuario. Permitirá editar los campos name, lastName, y roleId (cambiar el rol del usuario)

--

1. Add Component/UserFormPUT.jsx file
2. Test

_I used 'formik' and 'react-bootstrap'_

<img width="1280" alt="Screen Shot 2021-11-10 at 09 14 46" src="https://user-images.githubusercontent.com/85419447/141114402-9d5e2339-99ff-4e90-b870-65df75708fda.png">
<img width="1280" alt="Screen Shot 2021-11-10 at 09 14 53" src="https://user-images.githubusercontent.com/85419447/141114417-d46e779e-f734-4719-903b-8c3c890e2b23.png">

2021-11-10 13:52 UTC, andresmonsa approved these changes

2021-11-11 20:09 UTC, dvelezroman commented
Faltaria el input para la imagen del user

2021-11-12 13:08 UTC, dvelezroman requested changes, later dismissed
Faltaria el input para la imagen del User

2021-11-12 15:03 UTC, andresmonsa commented
No debería recibir el ID del usuario que se va a cambiar? para poder hacer desp la request.

2021-11-16 14:29 UTC, jpuery71292 approved these changes

2021-11-16 19:30 UTC, maxipaci approved these changes

2021-11-17 12:19 UTC, merged