OT90-637
alkemyTech/OT-90-Client pull request #3
Opened 2021-10-28 13:39 UTC by benjaminPla

COMO: Usuario
QUIERO: Visualizar el header de la pagina
PARA: Acceder a las opciones que tiene

Criterios de aceptación: El componente Header mostrará el logo obtenido del endpoint de datos públicos, y un menú de navegación, ambos elementos de forma dinámica. Para el menú, será un array de ítems de navegación, con un texto y una ruta

---

1. Create Header component, notice that i used Pokemon API to call and text purposes.
<img width="1280" alt="Screen Shot 2021-10-28 at 10 31 52" src="https://user-images.githubusercontent.com/85419447/139267361-90c5462b-c71d-4043-95bf-dd62ebb5fa25.png">

 _i propose to delete and clean all the examples_

2021-10-28 14:23 UTC, dvelezroman requested changes
This PR should merge after Routes PR

2021-10-28 18:26 UTC, andresmonsa approved these changes

2021-10-28 18:26 UTC, andresmonsa commented on src/Component/Header.jsx
> +    fetch('https://pokeapi.co/api/v2/pokemon/ditto')
it could receive the information by props in order to make the component reusable.

2021-10-28 18:26 UTC, andresmonsa commented on src/Component/Header.jsx
> +          <img src={publicData.sprites.front_default} alt={publicData.name} />
https://drive.google.com/drive/u/0/folders/1q-t5pTX3FA7bf-2kDnGq-99EUfkUQ7iZ

The Logo

2021-10-28 18:26 UTC, andresmonsa commented on src/Component/Header.jsx
> +  console.log(publicData)
you forgot to delete the console.log

2021-10-28 19:13 UTC, benjaminPla commented on src/Component/Header.jsx
> +  console.log(publicData)
nice! tx

2021-10-28 19:14 UTC, benjaminPla commented on src/Component/Header.jsx
> +    fetch('https://pokeapi.co/api/v2/pokemon/ditto')
could be, maybe calling it from a parent, but its a header. i am open to suggestions.

2021-10-28 21:58 UTC, dvelezroman commented
Completar layout de header para los botones.. seguir el figma

2021-10-29 20:40 UTC, dvelezroman approved these changes

2021-10-29 20:40 UTC, dvelezroman commented on src/App.jsx
>        <header className="App-header">
good

2021-11-01 17:50 UTC, verteramofederico approved these changes

2021-11-01 21:30 UTC, merged