Change en servicios upload, y en errores por carga
alkemyTech/OT-90-Client pull request #34
Opened 2021-11-11 16:30 UTC by jpuery71292

2021-11-11 18:46 UTC, andresmonsa approved these changes

2021-11-11 18:46 UTC, andresmonsa commented on src/Component/AWS.jsx
> +require('dotenv').config()
creo que esto no hacía falta.

2021-11-11 20:07 UTC, dvelezroman commented on src/Component/AWS.jsx
> +require('dotenv').config()
no hace falta....

2021-11-11 20:07 UTC, dvelezroman requested changes

2021-11-11 20:07 UTC, dvelezroman commented on src/Component/AWS.jsx
> +require('dotenv').config()
quitar esto y la dependencia dotenv

2021-11-12 12:15 UTC, jpuery71292 commented on src/Component/AWS.jsx
> +require('dotenv').config()
ahí quedo sin la llamada a dotenv

2021-11-12 14:42 UTC, dvelezroman approved these changes

2021-11-12 17:52 UTC, andresmonsa approved these changes

2021-11-12 17:52 UTC, verteramofederico approved these changes

2021-11-14 14:10 UTC, merged