OT90-686
alkemyTech/OT-90-Client pull request #35
Opened 2021-11-11 17:59 UTC by benjaminPla

Acción de cerrar sesión

COMO: Usuario
QUIERO: Cerrar mi sesión
PARA: Desloguearme de la pagina

Criterios de aceptación: El cierre de sesión se realizará desde el cliente, eliminando todos los datos del usuario desde localStorage, y desde el store de Redux

--

1. Add localStorage on redux usersSlice.js file.
2. Test.

https://www.loom.com/share/cee64bbb31254fcfb0742656695756bc

2021-11-11 18:48 UTC, andresmonsa approved these changes

2021-11-11 20:06 UTC, dvelezroman approved these changes

2021-11-11 21:46 UTC, maxipaci approved these changes

2021-11-15 21:13 UTC, dvelezroman requested changes

2021-11-15 21:13 UTC, dvelezroman commented on src/app/userSlice.js
>        state.user = {}
state.user = null

2021-11-17 02:25 UTC, dvelezroman approved these changes

2021-11-17 12:19 UTC, merged